config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'index#index'
  
  resources :quotes
  resources :employee_lists
  resources :building_details
  resources :elevators
  resources :batteries
  resources :columns
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  resources :messages
  resources :googlemaps
  resources :interventions
  resources :users
    
  get '/test', to: 'messages#patate'
  get 'termsAndConditions', to: 'index#termsAndConditions', as: "termsAndConditions"
  get 'privacy', to: 'index#privacy', as: "privacy"
  get 'commercial', to: 'index#commercialpage', as: "commercial"
  get 'residential', to: 'index#residentialpage', as: "residential"
  get 'index', to: 'index#index'
  post 'lead', to: 'leads#create', as: "leadcreate"
  get 'googlemap', to: 'googlemaps#index', as: "maps"
  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'
  get 'get_batteries_by_building/:building_id', to: 'batteries#get_batteries_by_building'
  get 'get_columns_by_battery/:battery_id', to: 'columns#get_columns_by_battery'
  get 'get_elevators_by_column/:column_id', to: 'elevators#get_elevators_by_column'
  get '/building_search' => 'buildings#building_search'
  get '/battery_search' => 'batteries#battery_search'
  get '/column_search' => 'columns#column_search'
  get '/elevator_search' => 'elevators#elevator_search'
  delete 'logout', to: 'sessions#destroy'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    else
      cannot :read, :admin
    end
   
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :buildings
    has_many :customers
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
    belongs_to :employee
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    belongs_to :address
    has_many :building_details
    has_many :batteries
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    belongs_to :address
    has_many :buildings
end

app/models/dim_customer.rb
class DimCustomer < SecondBase::Base
end

app/models/elevator.rb
require 'slack-notifier'
class Elevator < ApplicationRecord
    belongs_to :column
    after_update :twilio
    after_update :hello

    def hello
        puts '---------------'
        puts 'hello'
        puts '---------------'

        notifier = Slack::Notifier.new ENV['slack_key']
        notifier.ping "The Elevator #{id} with Serial Number #{serial_number} changed status from #{status_before_last_save} to #{status} "
    end    

    # def do_something
    #     puts '------does it work ?------'
    #     ENV['slack_key']
    #     notifier = Slack::Notifier.new "https://hooks.slack.com/services/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L"
    #     notifier.ping "Hello World"
    # end  
    
    def twilio
        if @elevator_status_changed == "Intervention" then 
            
          account_sid = ENV['TWILIO_ACCOUNT_SID']
          auth_token = ENV['TWILIO_AUTH_TOKEN']
          @client = Twilio::REST::Client.new(account_sid, auth_token)
  
          message = @client.messages.create(
              to: '+14186557999',
              from: '+15203416848',
              body: "The status from elevator #{id} in building #{column.battery.building.id} has changed from #{status_before_last_save} to #{status}."
          )
        end
    end
end
 

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_many :batteries
end

app/models/fact_contact.rb
class FactContact < SecondBase::Base
end

app/models/fact_elevator.rb
class FactElevator < SecondBase::Base
end

app/models/fact_quote.rb
class FactQuote < SecondBase::Base
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord

end

app/models/quote.rb
class Quote < ApplicationRecord
 
end

app/models/stat.rb
class Stat < SecondBase::Base
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
  has_one :employee
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  include ActiveModel::Dirty
  require 'rubygems'
  require 'twilio-ruby'
  # before_save :do_something, if: :elevator_status_changed?
  before_action :set_elevator, only: %i[ show edit update destroy ]

  # GET /elevators or /elevators.json
  def index
    @elevators = Elevator.all
  end

  # GET /elevators/1 or /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = Elevator.new
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators or /elevators.json
  def create
    @elevator = Elevator.new(elevator_params)

    respond_to do |format|
      if @elevator.save
        format.html { redirect_to elevator_url(@elevator), notice: "Elevator was successfully created." }
        format.json { render :show, status: :created, location: @elevator }
       
          
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1 or /elevators/1.json
  def update
    
    respond_to do |format|
      if @elevator.update(elevator_params)
          format.html { redirect_to elevator_url(@elevator), notice: "Elevator was successfully updated." }
          format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1 or /elevators/1.json
  def destroy
    @elevator.destroy

    respond_to do |format|
      format.html { redirect_to elevators_url, notice: "Elevator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    # For dynamic dropdown lists in intervention form
    def get_elevators_by_column
      @elevators = Elevator.where("column_id = ?", params[:column_id])
      puts "*********************************"
      puts @elevators
      puts "*********************************"
      respond_to do |format|
        format.json { render :json => @elevators }
      end
    end
    def elevator_search
      if params[:column].present? && params[:column].strip != ""
        @elevators = Elevator.where("column_id = ?", params[:column])
      else
        @elevators = Elevator.all
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = Elevator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elevator_params
      params.require(:elevator).permit(:serial_number, :model, :type, :status, :commissioning_date, :last_inspection_date, :inspection_certificate, :information, :notes)
    end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.select :model, [ "Standard", "Premium", "Excelium" ] %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, [ "Residential", "Commercial", "Corporate", "Hybrid" ] %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, [ "Active", "Inactive", "Intervention" ] %>
  </div>

  <div class="field">
    <%= form.label :commissioning_date %>
    <%= form.date_select :commissioning_date %>
  </div>

  <div class="field">
    <%= form.label :last_inspection_date %>
    <%= form.date_select :last_inspection_date %>
  </div>

  <div class="field">
    <%= form.label :inspection_certificate %>
    <%= form.text_field :inspection_certificate %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elevators/edit.html.erb
<h1>Editing Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Show', @elevator %> |
<%= link_to 'Back', elevators_path %>

app/views/elevators/elevator_search.js.erb
$('#elevator_listing').html('<%= j render partial: "elevator_list", locals: {elevators: @elevators} %>')

app/views/elevators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elevators</h1>

<table>
  <thead>
    <tr>
      <th>Serial number</th>
      <th>Model</th>
      <th>Type</th>
      <th>Status</th>
      <th>Commissioning date</th>
      <th>Last inspection date</th>
      <th>Inspection certificate</th>
      <th>Information</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <tr>
        <td><%= elevator.serial_number %></td>
        <td><%= elevator.model %></td>
        <td><%= elevator.type %></td>
        <td><%= elevator.status %></td>
        <td><%= elevator.commissioning_date %></td>
        <td><%= elevator.last_inspection_date %></td>
        <td><%= elevator.inspection_certificate %></td>
        <td><%= elevator.information %></td>
        <td><%= elevator.notes %></td>
        <td><%= link_to 'Show', elevator %></td>
        <td><%= link_to 'Edit', edit_elevator_path(elevator) %></td>
        <td><%= link_to 'Destroy', elevator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elevator', new_elevator_path %>

app/views/elevators/new.html.erb
<h1>New Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serial number:</strong>
  <%= @elevator.serial_number %>
</p>

<p>
  <strong>Model:</strong>
  <%= @elevator.model %>
</p>

<p>
  <strong>Type:</strong>
  <%= @elevator.type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @elevator.status %>
</p>

<p>
  <strong>Commissioning date:</strong>
  <%= @elevator.commissioning_date %>
</p>

<p>
  <strong>Last inspection date:</strong>
  <%= @elevator.last_inspection_date %>
</p>

<p>
  <strong>Inspection certificate:</strong>
  <%= @elevator.inspection_certificate %>
</p>

<p>
  <strong>Information:</strong>
  <%= @elevator.information %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @elevator.notes %>
</p>

<%= link_to 'Edit', edit_elevator_path(@elevator) %> |
<%= link_to 'Back', elevators_path %>