config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'index#index'
  
  resources :quotes
  resources :employee_lists
  resources :building_details
  resources :elevators
  resources :batteries
  resources :columns
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  resources :messages
  resources :googlemaps
  resources :interventions
  resources :users
    
  get '/test', to: 'messages#patate'
  get 'termsAndConditions', to: 'index#termsAndConditions', as: "termsAndConditions"
  get 'privacy', to: 'index#privacy', as: "privacy"
  get 'commercial', to: 'index#commercialpage', as: "commercial"
  get 'residential', to: 'index#residentialpage', as: "residential"
  get 'index', to: 'index#index'
  post 'lead', to: 'leads#create', as: "leadcreate"
  get 'googlemap', to: 'googlemaps#index', as: "maps"
  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'
  get 'get_batteries_by_building/:building_id', to: 'batteries#get_batteries_by_building'
  get 'get_columns_by_battery/:battery_id', to: 'columns#get_columns_by_battery'
  get 'get_elevators_by_column/:column_id', to: 'elevators#get_elevators_by_column'
  get '/building_search' => 'buildings#building_search'
  get '/battery_search' => 'batteries#battery_search'
  get '/column_search' => 'columns#column_search'
  get '/elevator_search' => 'elevators#elevator_search'
  delete 'logout', to: 'sessions#destroy'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    else
      cannot :read, :admin
    end
   
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :buildings
    has_many :customers
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
    belongs_to :employee
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    belongs_to :address
    has_many :building_details
    has_many :batteries
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    belongs_to :address
    has_many :buildings
end

app/models/dim_customer.rb
class DimCustomer < SecondBase::Base
end

app/models/elevator.rb
require 'slack-notifier'
class Elevator < ApplicationRecord
    belongs_to :column
    after_update :twilio
    after_update :hello

    def hello
        puts '---------------'
        puts 'hello'
        puts '---------------'

        notifier = Slack::Notifier.new ENV['slack_key']
        notifier.ping "The Elevator #{id} with Serial Number #{serial_number} changed status from #{status_before_last_save} to #{status} "
    end    

    # def do_something
    #     puts '------does it work ?------'
    #     ENV['slack_key']
    #     notifier = Slack::Notifier.new "https://hooks.slack.com/services/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L"
    #     notifier.ping "Hello World"
    # end  
    
    def twilio
        if @elevator_status_changed == "Intervention" then 
            
          account_sid = ENV['TWILIO_ACCOUNT_SID']
          auth_token = ENV['TWILIO_AUTH_TOKEN']
          @client = Twilio::REST::Client.new(account_sid, auth_token)
  
          message = @client.messages.create(
              to: '+14186557999',
              from: '+15203416848',
              body: "The status from elevator #{id} in building #{column.battery.building.id} has changed from #{status_before_last_save} to #{status}."
          )
        end
    end
end
 

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_many :batteries
end

app/models/fact_contact.rb
class FactContact < SecondBase::Base
end

app/models/fact_elevator.rb
class FactElevator < SecondBase::Base
end

app/models/fact_quote.rb
class FactQuote < SecondBase::Base
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord

end

app/models/quote.rb
class Quote < ApplicationRecord
 
end

app/models/stat.rb
class Stat < SecondBase::Base
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
  has_one :employee
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/index/commercialpage.html.erb
<%= render "partials/header" %>

			<hr class="m-0" /><!-- 1px line separator -->


			<!-- BUTTON CALLOUT -->
			<a class="btn btn-xlg btn-danger fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Looking for more infos <br>   
					<strong>Commercial division</strong>
				</span>
			</a>
			<!-- /BUTTON CALLOUT -->


			
			<!-- Services -->
			<section id="services">
				<div class="container">

					<div class="row">
						<div class="col-sm-6">
							<%= image_tag("AdobeStock_commercial2", class: "img-fluid", alt: "img", bgposition:"center") %>
							<h3 class="mt-10">Commercial division</h3>
							<p>You have big projects ahead? Building or renovating, our commercial division is there for you!</p>
						</div>

						<div class="col-sm-6">
							<%= image_tag("AdobeStock_maintenance", class: "img-fluid", alt: "img", bgposition:"center") %>
							<h3 class="mt-10">Maintenance services</h3>
							<p>Our commercial division offers professional maintenance services that will help keep your existing system in good shape.</p>
						</div>
					</div>

				</div>
			</section>
			<!-- /Services -->

			


			<!-- Parallax En affaires ! -->
			<section class="parallax parallax-1" style="background-image: url(<%= asset_path 'AdobeStock_3slides.jpeg' %>)">
				<div class="overlay dark-5"><!-- dark overlay [1 to 9 opacity] --></div>

				<div class="container">

					<div class="text-center">
						<h2 class="fs-40 fw-300">Elevating your projects since 1976</h2>
							<%= link_to "GET A QUOTE", new_quote_path, :class => ["btn btn-blue btn-lg", "fa fa-angle-right"], 'data-turbolinks': false %>
						&nbsp; OR &nbsp; 
							<%= link_to "CONTACT US", "#{root_path}#contact", :class => ["btn btn-blue btn-lg", "fa fa-angle-right"], 'data-turbolinks': false %>
					</div>

				</div>
			</section>
			<!-- /Parallax -->

<%= render "partials/footer" %>

app/views/index/privacy.html.erb
<%= render "partials/header" %>

<body>Privacy Page : Under Construction<body>

<%= render "partials/footer" %>

app/views/index/residentialpage.html.erb
<%= render "partials/header" %>

			<hr class="m-0" /><!-- 1px line separator -->


			<!-- HEADER -->
			<h3 class="btn btn-xlg btn-danger fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Looking for more infos <br>   
					<strong>Residential division</strong>
				</span>
			</h3>
			<!-- /HEADER -->


			
			<!-- Services -->
			<section id="services">
				<div class="container">

					<div class="row">
						<div class="col-sm-6">
							<%= image_tag("AdobeStock_residential", class: "img-fluid", alt: "img", bgposition:"center") %>
							<h3 class="mt-10">Residential division</h3>
							<p>You have big projects ahead? Building or renovating, our residential division is there for you!</p>
						</div>

						<div class="col-sm-6">
							<%= image_tag("AdobeStock_maintenance", class: "img-fluid", alt: "img", bgposition:"center") %>
							<h3 class="mt-10">Maintenance services</h3>
							<p>Our residential division offers professional maintenance services that will help keep your existing system in good shape.</p>
						</div>
					</div>

				</div>
			</section>
			<!-- /Services -->

			


			<!-- Parallax En affaires ! -->
			<section class="parallax parallax-1" style="background-image: url(<%= asset_path 'AdobeStock_3slides.jpeg' %>)">
				<div class="overlay dark-5"><!-- dark overlay [1 to 9 opacity] --></div>

				<div class="container">

					<div class="text-center">
						<h2 class="fs-40 fw-300">Elevating your projects since 1976</h2>
							<%= link_to "GET A QUOTE", new_quote_path, :class => ["btn btn-blue btn-lg", "fa fa-angle-right"], 'data-turbolinks': false %>
						&nbsp; OR &nbsp; 
							<%= link_to "CONTACT US", "#{root_path}#contact", :class => ["btn btn-blue btn-lg", "fa fa-angle-right"], 'data-turbolinks': false %>
					</div>

				</div>
			</section>
			<!-- /Parallax -->

<%= render "partials/footer" %>

app/views/index/termsAndConditions.html.erb
<%= render "partials/header" %>

<body>Terms & Conditions Page : Under Construction<body>

<%= render "partials/footer" %>

app/views/partials/_footer.html.erb
			<!-- FOOTER -->
			<footer id="footer">
				<div class="container">


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
								We have the conviction that we create the most innovative and reliable products on the market. <br>
								Contact us today for any questions you might have.
							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						<!-- col #2 -->
						<div class="col-md-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

							<!-- Newsletter Form -->
							<p>Subscribe to Our Newsletter to See What is Coming and Going !</p>

							<form class="validate" action="/assets/php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="btn btn-danger" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->


						</div>
						<!-- /col #2 -->

					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li><%= link_to "Terms & Conditions", termsAndConditions_path, 'data-turbolinks': false %></li>
							<li>&bull;</li>
							<li><%= link_to "Privacy", privacy_path, 'data-turbolinks': false %></li>
						</ul>
						&copy; All Rights Reserved, Rocket Elevators
					</div>
				</div>

			</footer>
			<!-- /FOOTER -->

		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
	
		<%= link_to "", "#{root_path}#", id: "toTop", 'data-turbolinks': false %>
	</body>
</html>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-RVYH8KVJ27"></script>
		<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-RVYH8KVJ27');
		</script>
		<meta charset="utf-8" />
		<title>Rocket Elevators - Elevate Safety, Speed and Style</title>
		<meta name="description" content="Since 1976, Rocket Elevators is elevating safety, speed and style. Check out our residential elevator products and services at www.mathieubernier.com" />
		<meta name="Author" content="Monique Payment-Boulanger [www.monichan.com]" />

		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

		<!-- JAVASCRIPT FILES -->
		<script>var plugins_path = '/assets/plugins/';</script>
		
	</head>

	<!--
		AVAILABLE BODY CLASSES:
		
		smoothscroll 			= create a browser smooth scroll
		enable-animation		= enable WOW animations

		bg-grey					= grey background
		grain-grey				= grey grain background
		grain-blue				= blue grain background
		grain-green				= green grain background
		grain-blue				= blue grain background
		grain-orange			= orange grain background
		grain-yellow			= yellow grain background
		
		boxed 					= boxed layout
		pattern1 ... patern11	= pattern background
		menu-vertical-hide		= hidden, open on click
		
		BACKGROUND IMAGE [together with .boxed class]
		data-background="assets/images/_smarty/boxed_background/1.jpg"
	-->
	<%# <body class="smoothscroll enable-animation"> %>


		<!-- wrapper -->
		<div id="wrapper">

			<!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!

				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->
			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->
						<%= link_to image_tag("R2", alt: "Logo"),  "#{root_path}#toTop", :class => "logo float-left scrollTo", 'data-turbolinks': false %>

						<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active"><!-- HOME -->
										<%= link_to "HOME", root_path, 'data-turbolinks': false %>
									</li>
									<li><!-- SERVICES -->
										<%= link_to "SERVICES", "#{root_path}#services", 'data-turbolinks': false %>
									</li>
									<li><!-- PORTFOLIO -->
										<%= link_to "PORTFOLIO", "#{root_path}#portfolio", 'data-turbolinks': false %>
									</li>
									<li><!-- NEWS -->
										<%= link_to "NEWS", "#{root_path}#news", 'data-turbolinks': false %>
									</li>
									<li><!-- CLIENTS -->
										<%= link_to "CLIENTS", "#{root_path}#clients", 'data-turbolinks': false %>
									</li>
									<li><!-- CONTACT -->
										<%= link_to "CONTACT", "#{root_path}#contact", 'data-turbolinks': false %>
									</li>
									<%# <li><!-- INTERVENTIONS --> %>
										<%# <%= link_to "INTERVENTIONS", new_intervention_path, 'data-turbolinks': false %>
									<%# </li> %>
									<%# <li><!-- DASHBOARD --> %>
										<%# <%= link_to "DASHBOARD", rails_admin_path, 'data-turbolinks': false %>
									<%# </li> %>
									<%# <li><!-- LOGIN --> %>
										<%# <%= link_to "LOGIN", rails_admin_path, 'data-turbolinks': false %>
										<%# <%= link_to "LOGOUT", destroy_user_session_path, method: :delete  %>
										
										<%# <% if !signed_in? %>
											<%# <%= link_to "LOGIN", rails_admin_path, 'data-turbolinks': false %>
										<%# <% elsif signed_in? %>
											<%# <%= link_to "LOGOUT", destroy_user_session_path, method: :delete %>
										<%# <% end %>
									<%# </li> %>
									<%# <li><!-- MAPSTEST --> %>
										<%# <%= link_to "MAPS", maps_path, 'data-turbolinks': false %>
									<%# </li> %>
									<div class="dropdown">
										<button class="dropbtn">LOGIN</button>
										<div class="dropdown-content">
											<a href="rails_admin_path">DASHBOARD</a>
											<a href="new_intervention_path">INTERVENTIONS</a>
											<a href="maps_path">MAPS</a>
											<% if signed_in? %>
												<a href="destroy_user_session_path">LOGOUT</a>
											<% end %>
										</div>
									</div>		
								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->

			</div>