config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'index#index'
  
  resources :quotes
  resources :employee_lists
  resources :building_details
  resources :elevators
  resources :batteries
  resources :columns
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  resources :messages
  resources :googlemaps
  resources :interventions
  resources :users
    
  get '/test', to: 'messages#patate'
  get 'termsAndConditions', to: 'index#termsAndConditions', as: "termsAndConditions"
  get 'privacy', to: 'index#privacy', as: "privacy"
  get 'commercial', to: 'index#commercialpage', as: "commercial"
  get 'residential', to: 'index#residentialpage', as: "residential"
  get 'index', to: 'index#index'
  post 'lead', to: 'leads#create', as: "leadcreate"
  get 'googlemap', to: 'googlemaps#index', as: "maps"
  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'
  get 'get_batteries_by_building/:building_id', to: 'batteries#get_batteries_by_building'
  get 'get_columns_by_battery/:battery_id', to: 'columns#get_columns_by_battery'
  get 'get_elevators_by_column/:column_id', to: 'elevators#get_elevators_by_column'
  get '/building_search' => 'buildings#building_search'
  get '/battery_search' => 'batteries#battery_search'
  get '/column_search' => 'columns#column_search'
  get '/elevator_search' => 'elevators#elevator_search'
  delete 'logout', to: 'sessions#destroy'

end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  require 'rubygems'
  require 'rest_client'
  require 'json'
  require 'devise'
  
  before_action :authenticate_user!
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    # @currentUser = current_user.find(params[:id])
    # @currentUser = "#{current_user.id}" + " " + current_user.email
    # @employee_id = Employee.all.map{ |e| [ "#{e.id}" + " " + e.first_name + " " + e.last_name, e.id ] }
    # @customer_id = "Customer.id + " " + Customer.company_name"
    # @building_id = Building.all.select{ |bu| bu.customer_id  == @customer_id }.map{ |bu| [ "#{bu.id}" + " " + bu.number_and_street, bu.id] }
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)
      @intervention.author = current_user.id
      @intervention.customer_id = params[:customer_id]
      @intervention.building_id = params[:building_id]
      @intervention.battery_id = params[:battery_id]
      @intervention.column_id = params[:column_id]
      @intervention.elevator_id = params[:elevator_id]
      @intervention.employee_id = params[:employee_id]
      @intervention.report = params[:report]
      @customer = Customer.find(params[:customer_id])
      
    respond_to do |format|
      if @intervention.save
        intervention_request = {
          email: "#{@current_user.email}", 
          priority: 1, 
          status: 2,
          type: "Incident",
          subject: "Incident for #{@customer.company_name} from employee ##{@intervention.author}",
          description: "This incident request from employee ID #{@intervention.author} is for our customer #{@customer.company_name}. 
          Their bulding ##{@intervention.building_id} needs an intervention to:
          Battery ##{@intervention.battery_id}
          Column ##{@intervention.column_id}
          Elevator ##{@intervention.elevator_id}
          The intervention has been assigned to the employee ##{@intervention.employee_id}.
          Description of the incident: #{@intervention.report}"
        }.to_json
        puts "&&&&&&&&&&&&&&&&&&&&&&&&"
        puts "#{@current_user.email}"
        puts "#{@customer.company_name}"
        puts "#{@intervention.author}"
        puts "#{@intervention.building_id}"
        puts "#{@intervention.column_id}"
        puts "#{@intervention.elevator_id}"
        puts "#{@intervention.employee_id}"
        puts "#{@intervention.report}"
        puts "&&&&&&&&&&&&&&&&&&&&&&&&"
        
        # intervention_request_ticket = RestClient::Request.execute(
        #   method: :post, 
        #   url: 'https://codeboxx3519.freshdesk.com/api/v2/tickets',
        #   # user: 'Np2N3cPBQLFWVi4GVYD',
        #   user: ENV["freshdesk_api_key"],
        #   password: "x",
        #   headers: {
        #     content_type: "application/json"
        #   },
        #   payload: intervention_request
        # )
        # puts intervention_request_ticket

        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :intervention_started_at, :intervention_ended_at, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_battery_list.html.erb
<%# <% batteries.each do |battery| %> %>
  <%# <%= battery.id %> %>
  <%# <%= battery.status %> %>
  <%# <hr /> %>
<%# <% end %> %>

app/views/interventions/_building_list.html.erb
<% buildings.each do |building| %>
  <%= building.id %>
  <%= building.building_administrator_full_name %>
  <hr />
<% end

app/views/interventions/_column_list.html.erb
<%# <% columns.each do |column| %> %>
  <%# <%= column.id %> %>
  <%# <%= column.status %> %>
  <%# <hr /> %>
<%# <% end %> %>

app/views/interventions/_elevator_list.html.erb
<%# <% elevators.each do |elevator| %> %>
  <%# <%= elevator.id %> %>
  <%# <%= elevator.serial_number %> %>
  <%# <hr /> %>
<%# <% end %> %>

app/views/interventions/_form.html.erb
<%# Interventions Form %>
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row no-gutters wow slideInUp" data-wow-duration="1s">
    <div class="col-md-12 home-form">
      <%= form_tag(building_search_path, method: "get", class: "form-inline", remote: true) do %>
      <div id="author">
        <%= form.hidden_field current_user.id, class: "formFieldReadOnly", readonly: true %>
      </div>
      <div id="step_1">
        <%= form.label "Step 1 - Select Customer" %>
        <%= select_tag :customer_id, options_from_collection_for_select(Customer.all, "id", "id"), :required => true, prompt: "< Select customer>", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="step_2">
        <%= form.label "Step 2 - Select Building" %>
        <%= select_tag :building_id, options_from_collection_for_select(Building.all, "id", "id"), :required => true, prompt: "< Select building >", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="step_3">
        <%= form.label "Step 3 - Select Battery" %>
        <%= select_tag :battery_id, options_from_collection_for_select(Battery.all, "id", "id"), :required => true, prompt: "< Select battery >", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="step_4">
        <%= form.label "Step 4 - Select Column" %>
        <%= select_tag :column_id, options_from_collection_for_select(Column.all, "id", "id"), prompt: "None", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="step_5">
        <%= form.label "Step 5 - Select Elevator" %>
        <%= select_tag :elevator_id, options_from_collection_for_select(Elevator.all, "id", "id"), prompt: "None", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="employee">
        <%= form.label "Assigned Employee" %>
        <%= select_tag :employee_id, options_from_collection_for_select(Employee.all, "id", "id"), prompt: "None", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      </div>
      <div id="intervention_started_at">
        <%= hidden_field_tag :intervention_started_at %>
      </div>
      <div id="intervention_ended_at">
        <%= hidden_field_tag :intervention_ended_at %>
      </div>
      <div id="result">
        <%= hidden_field_tag :result %>
      </div>
      <div id="report">
        <%= form.label "Description" %>
        <%= text_area_tag :report %>
      </div>
      <div id="status">
        <%= hidden_field_tag :status %>
      </div>
      <div class="actions">
      <%= form.submit "Submit", :class => ["btn btn-danger", "fa fa-check"], :method => :post %>
    </div>
  <% end %>
    </div>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<%= render "partials/header" %>

<%# Editing Interventions %>
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Home', root_path, 'data-turbolinks': false %>

<%= render "partials/footer" %>

app/views/interventions/index.html.erb
<%# Interventions Index %>
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Customer</th>
      <th>Building</th>
      <th>Battery</th>
      <th>Column</th>
      <th>Elevator</th>
      <th>Employee</th>
      <th>Intervention started at</th>
      <th>Intervention ended at</th>
      <th>Result</th>
      <th>Report</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author %></td>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.building_id %></td>
        <td><%= intervention.battery_id %></td>
        <td><%= intervention.column_id %></td>
        <td><%= intervention.elevator_id %></td>
        <td><%= intervention.employee_id %></td>
        <td><%= intervention.intervention_started_at %></td>
        <td><%= intervention.intervention_ended_at %></td>
        <td><%= intervention.result %></td>
        <td><%= intervention.report %></td>
        <td><%= intervention.status %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<%= render "partials/header" %>

<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Home', root_path, 'data-turbolinks': false %>

<%= render "partials/footer" %>

app/views/interventions/show.html.erb
<%= render "partials/header" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @intervention.customer_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @intervention.building_id %>
</p>

<p>
  <strong>Battery:</strong>
  <%= @intervention.battery_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @intervention.column_id %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @intervention.elevator_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Intervention started at:</strong>
  <%= @intervention.intervention_started_at %>
</p>

<p>
  <strong>Intervention ended at:</strong>
  <%= @intervention.intervention_ended_at %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Home', root_path, 'data-turbolinks': false %>

<%= render "partials/footer" %>